/**
 * Enum representing valid industry values for HubSpot companies.
 * These values must match exactly with HubSpot's predefined industry options.
 */
export enum HubSpotIndustry {
  ACCOUNTING = 'ACCOUNTING',
  ADVERTISING_AND_MARKETING = 'ADVERTISING_AND_MARKETING',
  AEROSPACE = 'AEROSPACE',
  AGRICULTURE = 'AGRICULTURE',
  ARCHITECTURE_AND_PLANNING = 'ARCHITECTURE_AND_PLANNING',
  ARTS_AND_ENTERTAINMENT = 'ARTS_AND_ENTERTAINMENT',
  AUTOMOTIVE = 'AUTOMOTIVE',
  BANKING_AND_FINANCE = 'BANKING_AND_FINANCE',
  BIOTECHNOLOGY = 'BIOTECHNOLOGY',
  BROADCASTING = 'BROADCASTING',
  BUSINESS_SERVICES = 'BUSINESS_SERVICES',
  CHEMICALS = 'CHEMICALS',
  CIVIL_ENGINEERING = 'CIVIL_ENGINEERING',
  COMPUTER_HARDWARE = 'COMPUTER_HARDWARE',
  COMPUTER_SOFTWARE = 'COMPUTER_SOFTWARE',
  CONSTRUCTION = 'CONSTRUCTION',
  CONSUMER_ELECTRONICS = 'CONSUMER_ELECTRONICS',
  CONSUMER_GOODS = 'CONSUMER_GOODS',
  CONSUMER_SERVICES = 'CONSUMER_SERVICES',
  DEFENSE = 'DEFENSE',
  EDUCATION = 'EDUCATION',
  ENERGY = 'ENERGY',
  ENGINEERING = 'ENGINEERING',
  ENVIRONMENTAL_SERVICES = 'ENVIRONMENTAL_SERVICES',
  FINANCIAL_SERVICES = 'FINANCIAL_SERVICES',
  FOOD_AND_BEVERAGE = 'FOOD_AND_BEVERAGE',
  GOVERNMENT = 'GOVERNMENT',
  HEALTHCARE = 'HEALTHCARE',
  HOSPITALITY = 'HOSPITALITY',
  INFORMATION_TECHNOLOGY_AND_SERVICES = 'INFORMATION_TECHNOLOGY_AND_SERVICES',
  INSURANCE = 'INSURANCE',
  LEGAL_SERVICES = 'LEGAL_SERVICES',
  LIFE_SCIENCES = 'LIFE_SCIENCES',
  MANUFACTURING = 'MANUFACTURING',
  MEDIA_PRODUCTION = 'MEDIA_PRODUCTION',
  MEDICAL_DEVICES = 'MEDICAL_DEVICES',
  MINING_AND_METALS = 'MINING_AND_METALS',
  NONPROFIT = 'NONPROFIT',
  OIL_AND_ENERGY = 'OIL_AND_ENERGY',
  PHARMACEUTICALS = 'PHARMACEUTICALS',
  PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES',
  REAL_ESTATE = 'REAL_ESTATE',
  RETAIL = 'RETAIL',
  TELECOMMUNICATIONS = 'TELECOMMUNICATIONS',
  TEXTILES = 'TEXTILES',
  TRANSPORTATION = 'TRANSPORTATION',
  TRAVEL_AND_TOURISM = 'TRAVEL_AND_TOURISM',
  UTILITIES = 'UTILITIES',
  VENTURE_CAPITAL_AND_PRIVATE_EQUITY = 'VENTURE_CAPITAL_AND_PRIVATE_EQUITY',
  WAREHOUSING = 'WAREHOUSING',
  WHOLESALE = 'WHOLESALE'
}

/**
 * Type guard to check if a string is a valid HubSpot industry value
 * @param value - The string to check
 * @returns True if the value is a valid HubSpot industry
 */
export function isValidHubSpotIndustry(value: string): value is HubSpotIndustry {
  return Object.values(HubSpotIndustry).includes(value as HubSpotIndustry);
}

/**
 * Interface for industry-related validation errors
 */
export interface IndustryValidationError {
  code: 'INVALID_INDUSTRY';
  message: string;
  value: string;
  validOptions?: string[];
} 